notifications:
    email: false

sudo: required
language: rust
before_install: 
    - sudo apt-get install tree
    - sudo apt-get install rubygems
    - sudo gem install os
script: rake
after_script: rake test
